-- Updating the positions for existing staff records
UPDATE Staff SET Position = CASE 
    WHEN Staff_ID = 701 THEN 'Inventory'
    WHEN Staff_ID = 702 THEN 'Sales'
    WHEN Staff_ID = 703 THEN 'Sales'
    WHEN Staff_ID = 704 THEN 'Marketing'
    WHEN Staff_ID = 705 THEN 'Manager'
    WHEN Staff_ID = 706 THEN 'Manager'
    WHEN Staff_ID = 707 THEN 'Manager'
    WHEN Staff_ID = 708 THEN 'Manager'
    WHEN Staff_ID = 709 THEN 'Manager'
    WHEN Staff_ID = 710 THEN 'Personal Training'
    WHEN Staff_ID = 711 THEN 'Personal Training'
    WHEN Staff_ID = 712 THEN 'Sales'
    WHEN Staff_ID = 713 THEN 'Inventory'
    WHEN Staff_ID = 714 THEN 'Sales'
    WHEN Staff_ID = 715 THEN 'Customer Service'
    WHEN Staff_ID = 716 THEN 'Manager'
    WHEN Staff_ID = 717 THEN 'Sales'
    WHEN Staff_ID = 718 THEN 'Inventory'
    WHEN Staff_ID = 719 THEN 'Sales'
    WHEN Staff_ID = 720 THEN 'Customer Service'
    WHEN Staff_ID = 721 THEN 'Manager'
    WHEN Staff_ID = 722 THEN 'Personal Training'
    WHEN Staff_ID = 723 THEN 'Inventory'
    WHEN Staff_ID = 724 THEN 'Sales'
    WHEN Staff_ID = 725 THEN 'Customer Service'
    WHEN Staff_ID = 726 THEN 'Manager'
    WHEN Staff_ID = 727 THEN 'Sales'
    WHEN Staff_ID = 728 THEN 'Personal Training'
    WHEN Staff_ID = 729 THEN 'Inventory'
    WHEN Staff_ID = 730 THEN 'Sales'
    WHEN Staff_ID = 731 THEN 'Customer Service'
    WHEN Staff_ID = 732 THEN 'Manager'
    WHEN Staff_ID = 733 THEN 'Sales'
    WHEN Staff_ID = 734 THEN 'Personal Training'
    WHEN Staff_ID = 735 THEN 'Inventory'
    WHEN Staff_ID = 736 THEN 'Sales'
    WHEN Staff_ID = 737 THEN 'Customer Service'
    WHEN Staff_ID = 738 THEN 'Manager'
    WHEN Staff_ID = 739 THEN 'Sales'
    WHEN Staff_ID = 740 THEN 'Personal Training'
    WHEN Staff_ID = 741 THEN 'Maintenance'
    WHEN Staff_ID = 742 THEN 'Maintenance'
    WHEN Staff_ID = 743 THEN 'Maintenance'
    WHEN Staff_ID = 744 THEN 'Maintenance'
    WHEN Staff_ID = 745 THEN 'Maintenance'
    WHEN Staff_ID = 746 THEN 'Personal Training'
    WHEN Staff_ID = 747 THEN 'Wellness'
    WHEN Staff_ID = 748 THEN 'Childcare'
    WHEN Staff_ID = 749 THEN 'Marketing'
    WHEN Staff_ID = 750 THEN 'Administration'
END
WHERE Staff_ID BETWEEN 701 AND 750;

select * from staff;

